dependencies:
  flutter:
    sdk: flutter
  
  # Camera & Gallery
  camera: ^0.10.5
  gallery_saver_plus: ^3.2.9
  
  # Location (perbaiki versi)
  geolocator: ^11.1.0
  geocoding: ^3.0.0  # ← TAMBAHKAN
  
  # Permissions
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Image Processing
  image: ^4.1.7
  
  # HTTP
  http: ^1.2.0
  
  # Other
  intl: ^0.19.0
  share_plus: ^9.0.0
  flutter_svg: ^2.0.9
